version: 2.1
jobs:
  checkout_code:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/lybc-web
    steps:
      - checkout
      - save_cache:
          key: v1-repo-$CIRCLE_SHA1
          paths:
            - ~/lybc-web
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/lybc-web
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Restoring dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/lybc-web
    steps:
      - restore_cache:
          key: v1-repo-$CIRCLE_SHA1
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Restoring dependencies
          command: yarn install
      - run:
          name: Running test
          command: yarn test
  publish:
    environment:
      - IMAGE_NAME: lautin0/lybc-web
      - IMAGE_TAG: 1.0.0-web
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/lybc-web
    steps:
      - restore_cache:
          key: v1-repo-$CIRCLE_SHA1
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Restoring dependencies
          command: yarn install
      - deploy:
          command: |
            git config --global user.name $GH_NAME
            yarn run deploy
workflows:
  version: 2.1
  run_test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - build
  run_publish:
    jobs:
      - checkout_code:
          filters:
            branches:
              only: master
      - publish:
          filters:
            branches:
              only: master
          requires:
            - checkout_code
