# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

on:
  push:
    branches:
      - master
    branches-ignore:
      - gh-pages

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test

  deploy:
    requires:
      build
    filters:
      branches:
        only: master
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Deploy if tests pass and branch is Master
          command: |
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME
              CI=false npm run deploy

